name: Deploy postgresql api

on:
  push:
    branches: ["master"]

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: echo 'hello world ...'
      - run: ls -la
      #- run: docker build -t postgres/pg-restapi .
      #- run: docker images
      - run: touch .env
      - run: echo  'DEV_DATABASE_URL=postgres://postgres:piplorexplurex@localhost:5432/restapi{{}}' >> .env
      - run: cat .env
