name: Deploy-postgresql-api

on:
  push:
    branches: ["master"]

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: echo 'hello world ..'
      - run: ls -la
      - run: touch .env
      - run: echo 'DATABASE_URL=${{secrets.PG_CONN}}'  >> .env
      - run: cat .env

      # Install dependencies (descomentar si es necesario)
      - run: npm install

      # Construcci칩n de la imagen Docker
      - run: docker build -t joseantonioortiz/pgbackendapi:${{github.sha}} .

      # Ver las im치genes Docker creadas
      - run: docker images

      # Iniciar sesi칩n en Docker Hub
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
      # Subir la imagen a Docker Hub
      - name: docker push
        run: docker push ${{ secrets.DOCKER_USER}}/pgbackendapi:${{github.sha}}

      # Probar que la API est치 corriendo (opcional)
      - run: curl localhost:8080

