name: Deploy-postgresql-api

on:
  push:
    branches: ["master"]

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: echo 'Creando archivo .env...'
      - run: echo 'DEV_DATABASE_URL=${{ secrets.PG_CONN }}' >> .env
      - run: cat .env

      - run: npm install

      - run: docker build -t ${{ secrets.DOCKER_USER }}/pgbackendapi:${{ github.sha }} .

      - name: Etiquetar imagen como latest (opcional pero útil)
        run: docker tag ${{ secrets.DOCKER_USER }}/pgbackendapi:${{ github.sha }} ${{ secrets.DOCKER_USER }}/pgbackendapi:latest

      - name: Login DockerHub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Push imagen con SHA
        run: docker push ${{ secrets.DOCKER_USER }}/pgbackendapi:${{ github.sha }}

      - name: Push imagen como latest
        run: docker push ${{ secrets.DOCKER_USER }}/pgbackendapi:latest
